version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginxServer
    ports:
      - "8000:8000"
    volumes:
      - ./company:/company
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - app
  app:
    build: .
    container_name: djangoAPI
    command: bash -c "gunicorn company.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./company:/company
      - /static:/static 
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"