# Generated by Django 3.1.7 on 2021-02-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
